name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform:
    name: 'Terraform'
    defaults:
      working-directory: ./terraform
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, test]
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ENVIRONMENT: ${{ matrix.environment }}
      TF_WORKSPACE: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.9
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=${{ matrix.environment }}-tfplan
      - name: Terraform Apply
        id: apply
        run : terraform apply ${{ matrix.environment }}-tfplan
